version: 2
updates:
    - package-ecosystem: 'npm' # See documentation for possible values
      directory: '/' # Location of package manifests
      schedule:
          interval: 'weekly'
      reviewers:
          - 'shawnlong636'
      groups:
          dev-packages-non-major:
              applies-to: version-updates
              update-types:
                  - 'minor'
                  - 'patch'
              patterns:
                  - '*'
          dev-packages-major:
              applies-to: version-updates
              update-types:
                  - 'major'
              patterns:
                  - '*'
              exclude-patterns:
                  - 'eslint' # Can't migrate to v9 yet - waiting for updates to our eslint plugins
      pull-request-limit: 0
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      reviewers:
          - 'shawnlong636'
      groups:
          github-actions-all:
              applies-to: version-updates
              patterns:
                  - '*'
      pull-request-limit: 0
