version: 2
updates:
  # Non-major dev package updates
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "weekly" # Adjust to your preferred update frequency
    allow:
      - dependency-type: "development"
    ignore:
      - update-types: ["version-update:semver-major"]
    labels:
      - "dev-packages-non-major"
    commit-message:
      prefix: "deps"
      include: "scope"
    target-branch: "dev"
    open-pull-requests-limit: 1
    rebase-strategy: "auto"
    versioning-strategy: "increase"

  # Major dev package updates
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "development"
    labels:
      - "dev-packages-major"
    commit-message:
      prefix: "deps"
      include: "scope"
    target-branch: "dev"
    open-pull-requests-limit: 1
    versioning-strategy: "widen"
    allow:
      - dependency-type: "development"
    rebase-strategy: "auto"
    versioning-strategy: "increase"