name: Deploy

on:
    workflow_run:
        workflows: ['Test']
        types: [completed]
        branches:
            - 'main'
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Load secrets
              uses: 1password/load-secrets-action@v1
              with:
                  export-env: true
              env:
                  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
                  PUBLIC_AMPLITUDE_API_KEY: 'op://Equipped/yepwyd5vgzbdlkicnshfmsnssq/credential'
                  PEPPER: 'op://Equipped/Equipped Auth Pepper/credential'
                  MAILERSEND_API_KEY: 'op://Equipped/MailerSend Api Key/credential'
                  VERCEL_TOKEN: 'op://Equipped/Vercel Token/token'
                  PLANETSCALE_SERVICE_TOKEN_ID: 'op://Equipped/PlanetScale Service Token/username'
                  PLANETSCALE_SERVICE_TOKEN: 'op://Equipped/PlanetScale Service Token/credential'
                  PSCALE_DB_NAME: 'op://Equipped/PlanetScale Service Token/database name'
                  PSCALE_ORG_NAME: 'op://Equipped/PlanetScale Service Token/organization name'
                  GH_TOKEN: 'op://Equipped/Github Access Token/password'
                  CLOUDFLARE_IMAGES_API_KEY: 'op://Equipped/CloudFlare Images API Key/credential'
                  USE_OPCLI: 'true'
            - uses: actions/checkout@v4
            - uses: planetscale/setup-pscale-action@v1
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: 'pnpm'

            - run: pnpm install
            - run: pnpm pscale:cred:create "production" "prod"
            - run: pnpm vercel:settings:pull
            - run: pnpm exec vercel build --prod
            - run: pnpm pscale:dr:apply
            - run: pnpm vercel:deploy:production
