name: Deploy

on:
    workflow_run:
        workflows: ['Test']
        types: [completed]
        branches:
            - 'main'
jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        permissions:
            contents: read
            pull-requests: write
        env:
            PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
            PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
            PUBLIC_AMPLITUDE_API_KEY: ${{ secrets.PUBLIC_AMPLITUDE_API_KEY }}
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            PEPPER: ${{ secrets.PEPPER }}
            GH_TOKEN: ${{ github.token }}
            MAILERSEND_API_KEY: ${{ secrets.MAILERSEND_API_KEY }}
        steps:
            - uses: actions/checkout@v4
            - uses: planetscale/setup-pscale-action@v1
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: 'pnpm'

            - run: pnpm install
            - run: pnpm pscale:cred:create "production" "prod"
            - run: pnpm vercel:settings:pull
            - run: pnpm exec vercel build --prod
            - run: pnpm pscale:dr:apply
            - run: pnpm vercel:deploy:production
