name: Deploy

on:
    workflow_run:
        workflows: ['Test']
        types: [completed]
        branches:
            - 'main'
jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
          PUBLIC_AMPLITUDE_API_KEY: ${{ secrets.PUBLIC_AMPLITUDE_API_KEY }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          PEPPER: ${{ secrets.PEPPER }}
          GH_TOKEN: ${{ github.token }}
        steps:
          - uses: actions/checkout@v3
          - uses: planetscale/setup-pscale-action@v1
          - uses: pnpm/action-setup@v2
            with:
              version: 8
          - uses: actions/setup-node@v3
            with:
              node-version: '20.x'
              cache: 'pnpm'

          - run: pnpm install
          - run: pnpm pscale:cred:create "ga-deploy-preview-${{ github.run_number }}"
          - run: pnpm vercel:settings:pull
          - run: pnpm exec vercel build --prod     
          - run: pnpm pscale:dr:apply
          - run: pnpm vercel:deploy:production